 import type { Metadata } from "next";
  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";

  import { ImgRedondaTelaInicial } from "../componentes/CardRedondo";
  import { TestimonialCarousel } from "../componentes/Carousel";

  import PhotoUser from "../componentes/PhotoUser";
  import { faUserTie, faChartLine, faHandshake } from '@fortawesome/free-solid-svg-icons';
  import Card from "@/componentes/Card";
  import NavBar from "@/componentes/Navbar";
  import Footer from "@/componentes/Footer";
  import {Banner} from "@/componentes/Banner";
  

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
  <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      
      <NavBar />
      {children}
      <Footer />
    </body>
  </html>
)
  }

