import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ImgRedondaTelaInicial } from "../componentes/CardRedondo";
import { TestimonialCarousel } from "../componentes/Carousel";

import PhotoUser from "../componentes/PhotoUser";
import { faUserTie, faChartLine, faHandshake } from '@fortawesome/free-solid-svg-icons';
import { Banner } from "../componentes/Banner";
import Card from "../componentes/Card";
import Footer from "../componentes/Footer";
import NavBar from "../componentes/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavBar />
        {children}

        <div className="">
        <Footer />
        </div>
        
      </body>
    </html>
  );
}

